//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace launcherDiscord.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("launcherDiscord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cygwin1 {
            get {
                object obj = ResourceManager.GetObject("cygwin1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general__ALT_ {
            get {
                return ResourceManager.GetString("general__ALT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general__ALT2_ {
            get {
                return ResourceManager.GetString("general__ALT2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general__ALT3_ {
            get {
                return ResourceManager.GetString("general__ALT3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general__ALT4_ {
            get {
                return ResourceManager.GetString("general__ALT4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general__ALT5_ {
            get {
                return ResourceManager.GetString("general__ALT5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general__ALT6_ {
            get {
                return ResourceManager.GetString("general__ALT6_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general__ALT7_ {
            get {
                return ResourceManager.GetString("general__ALT7_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general__FAKE_TLS_AUTO_ {
            get {
                return ResourceManager.GetString("general__FAKE_TLS_AUTO_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general__FAKE_TLS_AUTO_ALT_ {
            get {
                return ResourceManager.GetString("general__FAKE_TLS_AUTO_ALT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///chcp 65001 &gt;nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0..\&quot;
        ///set BIN=%~dp0..\bin\
        ///
        ///set LIST_TITLE=ZAPRET: Ultimate Fix
        ///set LIST_PATH=%~dp0..\lists\list-ultimate.txt
        ///set GMODE_FLAG_FILE=%BIN%gmode.flag
        ///set DISCORD_IPSET_PATH=%~dp0..\lists\ipset-discord.txt
        ///set CLOUDFLARE_IPSET_PATH=%~dp0..\lists\ipset-cloudflare.txt
        ///
        ///if exist &quot;%GMODE_FLAG_FILE%&quot; (
        ///    set &quot;GModeStatus=enabled&quot;
        ///    set &quot;GModeRange=1024-65535&quot;
        ///) else (
        ///    set &quot;GModeStatus=disabled&quot;
        ///    set &quot;GModeRange=0&quot;
        ///)
        ///
        ///start &quot;%LIST_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general__FAKE_TLS_AUTO_ALT2_ {
            get {
                return ResourceManager.GetString("general__FAKE_TLS_AUTO_ALT2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203.0.113.113/32
        ///.
        /// </summary>
        internal static string ipset_all {
            get {
                return ResourceManager.GetString("ipset_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ipset_all_txt {
            get {
                object obj = ResourceManager.GetObject("ipset_all_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloudflare-ech.com
        ///dis.gd
        ///discord-attachments-uploads-prd.storage.googleapis.com
        ///discord.app
        ///discord.co
        ///discord.com
        ///discord.design
        ///discord.dev
        ///discord.gift
        ///discord.gifts
        ///discord.gg
        ///discord.media
        ///discord.new
        ///discord.store
        ///discord.status
        ///discord-activities.com
        ///discordactivities.com
        ///discordapp.com
        ///discordapp.net
        ///discordcdn.com
        ///discordmerch.com
        ///discordpartygames.com
        ///discordsays.com
        ///discordsez.com
        ///yt3.ggpht.com
        ///yt4.ggpht.com
        ///yt3.googleusercontent.com
        ///googlevideo.com
        ///jnn-pa.googleapis. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string list_general {
            get {
                return ResourceManager.GetString("list_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] quic_initial_www_google_com {
            get {
                object obj = ResourceManager.GetObject("quic_initial_www_google_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///set &quot;LOCAL_VERSION=1.8.5&quot;
        ///
        ///:: External commands
        ///if &quot;%~1&quot;==&quot;status_zapret&quot; (
        ///    call :test_service zapret soft
        ///    call :tcp_enable
        ///    exit /b
        ///)
        ///
        ///if &quot;%~1&quot;==&quot;check_updates&quot; (
        ///    if not &quot;%~2&quot;==&quot;soft&quot; (
        ///        start /b service check_updates soft
        ///    ) else (
        ///        call :service_check_updates soft
        ///    )
        ///    exit /b
        ///)
        ///
        ///if &quot;%~1&quot;==&quot;load_game_filter&quot; (
        ///    call :game_switch_status
        ///    exit /b
        ///)
        ///
        ///
        ///if &quot;%1&quot;==&quot;admin&quot; (
        ///    echo Started with admin rights
        ///) else (
        ///    echo Reque [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tls_clienthello_www_google_com {
            get {
                object obj = ResourceManager.GetObject("tls_clienthello_www_google_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WinDivert {
            get {
                object obj = ResourceManager.GetObject("WinDivert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WinDivert64 {
            get {
                object obj = ResourceManager.GetObject("WinDivert64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] winws {
            get {
                object obj = ResourceManager.GetObject("winws", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
