//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace launcherDiscord.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("launcherDiscord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] cygwin1 {
            get {
                object obj = ResourceManager.GetObject("cygwin1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__ALT_ {
            get {
                return ResourceManager.GetString("general__ALT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__ALT10_ {
            get {
                return ResourceManager.GetString("general__ALT10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__ALT2_ {
            get {
                return ResourceManager.GetString("general__ALT2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__ALT3_ {
            get {
                return ResourceManager.GetString("general__ALT3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__ALT4_ {
            get {
                return ResourceManager.GetString("general__ALT4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///:: NOT RECOMMENDED
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__ALT5_ {
            get {
                return ResourceManager.GetString("general__ALT5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__ALT6_ {
            get {
                return ResourceManager.GetString("general__ALT6_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__ALT7_ {
            get {
                return ResourceManager.GetString("general__ALT7_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__ALT8_ {
            get {
                return ResourceManager.GetString("general__ALT8_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__ALT9_ {
            get {
                return ResourceManager.GetString("general__ALT9_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__FAKE_TLS_AUTO_ {
            get {
                return ResourceManager.GetString("general__FAKE_TLS_AUTO_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__FAKE_TLS_AUTO_ALT_ {
            get {
                return ResourceManager.GetString("general__FAKE_TLS_AUTO_ALT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__FAKE_TLS_AUTO_ALT2_ {
            get {
                return ResourceManager.GetString("general__FAKE_TLS_AUTO_ALT2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__FAKE_TLS_AUTO_ALT3_ {
            get {
                return ResourceManager.GetString("general__FAKE_TLS_AUTO_ALT3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__SIMPLE_FAKE_ {
            get {
                return ResourceManager.GetString("general__SIMPLE_FAKE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///chcp 65001 &gt; nul
        ///:: 65001 - UTF-8
        ///
        ///cd /d &quot;%~dp0&quot;
        ///call service.bat status_zapret
        ///call service.bat check_updates
        ///call service.bat load_game_filter
        ///echo:
        ///
        ///set &quot;BIN=%~dp0bin\&quot;
        ///set &quot;LISTS=%~dp0lists\&quot;
        ///cd /d %BIN%
        ///
        ///start &quot;zapret: %~n0&quot; /min &quot;%BIN%winws.exe&quot; --wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilter% --wf-udp=443,19294-19344,50000-50100,%GameFilter% ^
        ///--filter-udp=443 --hostlist=&quot;%LISTS%list-general.txt&quot; --hostlist-exclude=&quot;%LISTS%list-exclude.txt&quot; --ipset-exclude=&quot;%LISTS%ipset- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string general__SIMPLE_FAKE_ALT_ {
            get {
                return ResourceManager.GetString("general__SIMPLE_FAKE_ALT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 203.0.113.113/32
        ///.
        /// </summary>
        internal static string ipset_all {
            get {
                return ResourceManager.GetString("ipset_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.0.0.0/8
        ///127.0.0.0/8
        ///172.16.0.0/12
        ///192.168.0.0/16
        ///169.254.0.0/16
        ///::1
        ///fc00::/7
        ///fe80::/10.
        /// </summary>
        internal static string ipset_exclude {
            get {
                return ResourceManager.GetString("ipset_exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pusher.com
        ///live-video.net
        ///ttvnw.net
        ///twitch.tv
        ///mail.ru
        ///citilink.ru
        ///yandex.com
        ///nvidia.com
        ///donationalerts.com
        ///vk.com
        ///yandex.kz
        ///mts.ru
        ///multimc.org
        ///ya.ru
        ///dns-shop.ru
        ///habr.com
        ///3dnews.ru
        ///sberbank.ru
        ///ozon.ru
        ///wildberries.ru
        ///microsoft.com
        ///msi.com
        ///akamaitechnologies.com
        ///2ip.ru
        ///yandex.ru
        ///.
        /// </summary>
        internal static string list_exclude {
            get {
                return ResourceManager.GetString("list_exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cloudflare-ech.com
        ///encryptedsni.com
        ///cloudflareaccess.com
        ///cloudflareapps.com
        ///cloudflarebolt.com
        ///cloudflareclient.com
        ///cloudflareinsights.com
        ///cloudflareok.com
        ///cloudflarepartners.com
        ///cloudflareportal.com
        ///cloudflarepreview.com
        ///cloudflareresolve.com
        ///cloudflaressl.com
        ///cloudflarestatus.com
        ///cloudflarestorage.com
        ///cloudflarestream.com
        ///cloudflaretest.com
        ///dis.gd
        ///discord-attachments-uploads-prd.storage.googleapis.com
        ///discord.app
        ///discord.co
        ///discord.com
        ///discord.design
        ///discord.dev
        ///discord.gift
        ///disco [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string list_general {
            get {
                return ResourceManager.GetString("list_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на yt3.ggpht.com
        ///yt4.ggpht.com
        ///yt3.googleusercontent.com
        ///googlevideo.com
        ///jnn-pa.googleapis.com
        ///stable.dl2.discordapp.net
        ///wide-youtube.l.google.com
        ///youtube-nocookie.com
        ///youtube-ui.l.google.com
        ///youtube.com
        ///youtubeembeddedplayer.googleapis.com
        ///youtubekids.com
        ///youtubei.googleapis.com
        ///youtu.be
        ///yt-video-upload.l.google.com
        ///ytimg.com
        ///ytimg.l.google.com
        ///.
        /// </summary>
        internal static string list_google {
            get {
                return ResourceManager.GetString("list_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] quic_initial_www_google_com {
            get {
                object obj = ResourceManager.GetObject("quic_initial_www_google_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///set &quot;LOCAL_VERSION=1.9.0b&quot;
        ///
        ///:: External commands
        ///if &quot;%~1&quot;==&quot;status_zapret&quot; (
        ///    call :test_service zapret soft
        ///    call :tcp_enable
        ///    exit /b
        ///)
        ///
        ///if &quot;%~1&quot;==&quot;check_updates&quot; (
        ///    if not &quot;%~2&quot;==&quot;soft&quot; (
        ///        start /b service check_updates soft
        ///    ) else (
        ///        call :service_check_updates soft
        ///    )
        ///    exit /b
        ///)
        ///
        ///if &quot;%~1&quot;==&quot;load_game_filter&quot; (
        ///    call :game_switch_status
        ///    exit /b
        ///)
        ///
        ///
        ///if &quot;%1&quot;==&quot;admin&quot; (
        ///    echo Started with admin rights
        ///) else (
        ///    echo Requ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] tls_clienthello_4pda_to {
            get {
                object obj = ResourceManager.GetObject("tls_clienthello_4pda_to", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] tls_clienthello_www_google_com {
            get {
                object obj = ResourceManager.GetObject("tls_clienthello_www_google_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WinDivert {
            get {
                object obj = ResourceManager.GetObject("WinDivert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WinDivert64 {
            get {
                object obj = ResourceManager.GetObject("WinDivert64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] winws {
            get {
                object obj = ResourceManager.GetObject("winws", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
